### ISSUE TITLE
KeyError: 'categories'

### ISSUE THREAD

**Issue by HotCoCoC** [3D-FRONT-FUTURE/3D-FUTURE-AI-Challenge-Baseline#1]
Hello, when i try to execute this code，I had this problem

python tools/test.py configs/future3d_cascade_mask_rcnn_x101_64x4d_fpn_1x.py \
    checkpoints/future3d_cascade_mask_rcnn_x101_64x4d_fpn_1x-7487f640.pth \
    --show

KeyError: 'categories'
test.py reads val_set.json which hasn't the key word (categories).
What should I do?
Thanks a lot.

**Comment by BwCai** [comment]
The val_set.json shares the same 'categories' data with train_set.json. So you can copy it from train_set.json. 
Btw, val_set.json released in our competition does not contains segmentation ground-truth. If you want to evaluate your model, you should construct your own validation set from train_set.json.

**Comment by HotCoCoC** [comment]
Thank you very much. The problem has been solved
