### ISSUE TITLE
What is "level2_id" and "level3_id" ?

### ISSUE THREAD

**Issue by gyfastas** [3D-FRONT-FUTURE/3D-FUTURE-AI-Challenge-Baseline#2]
Hi! I notice that the "level2_id" is loaded as category of 2D images. Is that the same as "category" in "train_set.json"?

**Comment by shunming92** [comment]
level2_id and level3_id represents category names and fine-grained category names respectively.

category: 
{'Lighting': 0, 'Chair': 1, 'Table': 2, 'Bed': 3, 'Pier/Stool': 4, 'Sofa': 5, 'Cabinet/Shelf/Desk': 6}

fine-grained category
{0: 'Ceiling Lamp', 1: 'Lounge Chair / Book-chair / Computer Chair', 2: 'Dining Table', 3: 'Double Bed', 4: 'Dining Chair', 5: 'Pendant Lamp', 6: 'Footstool / Sofastool / Bed End Stool / Stool', 7: 'Two-seat Sofa', 8: 'Corner/Side Table', 9: 'Three-Seat / Multi-person sofa', 10: 'armchair', 11: 'Nightstand', 12: 'Tea Table', 13: 'Sideboard / Side Cabinet / Console', 14: 'TV Stand', 15: 'Wardrobe', 16: 'Dressing Table', 17: 'Drawer Chest / Corner cabinet', 18: 'Dressing Chair', 19: 'Wine Cooler', 20: 'Bookcase / jewelry Armoire', 21: 'Single bed', 22: 'L-shaped Sofa', 23: 'Desk', 24: 'Classic Chinese Chair', 25: 'Chaise Longue Sofa', 26: 'Shelf', 27: 'Bunk Bed', 28: 'Children Cabinet', 29: 'Barstool', 30: 'Round End Table', 31: 'Lazy Sofa', 32: 'Bed Frame', 33: 'Kids Bed'}
