### ISSUE TITLE
whereis utils to loss_and_miner_utils

### ISSUE THREAD

**Issue by IvanaXu** [3D-FRONT-FUTURE/3D-FUTURE-AI-Challenge-Baseline#3]
https://github.com/FUTURE-3D/FUTURE3D-AI-Challenge-Baseline/blob/809e2c1d4f5bcdaf1d8d33e4bbec64a134685bba/retrieval/models/pytorch_metric_learning/pytorch_metric_learning/losses/angular_loss.py#L6

**Comment by shunming92** [comment]
Hi, sorry for the late reply. I have uploaded relevant files, please re-download. 

Or you can download pytorch metric learning from this url(https://github.com/KevinMusgrave/pytorch-metric-learning).
